/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FidelidadRouteImport } from './routes/fidelidad'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadIdRouteImport } from './routes/propiedad.$id'
import { Route as AuthRegistroRouteImport } from './routes/auth.registro'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FidelidadRoute = FidelidadRouteImport.update({
  id: '/fidelidad',
  path: '/fidelidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadIdRoute = PropiedadIdRouteImport.update({
  id: '/propiedad/$id',
  path: '/propiedad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/auth/registro',
  path: '/auth/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/contratos': typeof ContratosRoute
  '/fidelidad': typeof FidelidadRoute
  '/perfil': typeof PerfilRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/contratos': typeof ContratosRoute
  '/fidelidad': typeof FidelidadRoute
  '/perfil': typeof PerfilRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/contratos': typeof ContratosRoute
  '/fidelidad': typeof FidelidadRoute
  '/perfil': typeof PerfilRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/contratos'
    | '/fidelidad'
    | '/perfil'
    | '/auth/login'
    | '/auth/registro'
    | '/propiedad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/contratos'
    | '/fidelidad'
    | '/perfil'
    | '/auth/login'
    | '/auth/registro'
    | '/propiedad/$id'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/contratos'
    | '/fidelidad'
    | '/perfil'
    | '/auth/login'
    | '/auth/registro'
    | '/propiedad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  ContratosRoute: typeof ContratosRoute
  FidelidadRoute: typeof FidelidadRoute
  PerfilRoute: typeof PerfilRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
  PropiedadIdRoute: typeof PropiedadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelidad': {
      id: '/fidelidad'
      path: '/fidelidad'
      fullPath: '/fidelidad'
      preLoaderRoute: typeof FidelidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad/$id': {
      id: '/propiedad/$id'
      path: '/propiedad/$id'
      fullPath: '/propiedad/$id'
      preLoaderRoute: typeof PropiedadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registro': {
      id: '/auth/registro'
      path: '/auth/registro'
      fullPath: '/auth/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  ContratosRoute: ContratosRoute,
  FidelidadRoute: FidelidadRoute,
  PerfilRoute: PerfilRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistroRoute: AuthRegistroRoute,
  PropiedadIdRoute: PropiedadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
